version: '3.4'

services:
  db:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: 'Y' 
      SA_PASSWORD: 'QbK2XEr6H8'
    ports:
        - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks: 
        - firstofall_network

  web:
    image: firstofallwebapi
    container_name: firstofallwebapi
    build:
      context: .
      dockerfile: src/FirstOfAll.WebApi/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    networks: 
      - firstofall_network

volumes:
  sqldata:

networks:
  firstofall_network:
    driver: bridge